# Generated by Django 2.0.9 on 2018-10-16 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_auto_20181016_1324'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='comment',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
